// <auto-generated />
using System;
using BTL_LTWEB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BTL_LTWEB.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251106162035_UpdateSchemaToMatchSQL")]
    partial class UpdateSchemaToMatchSQL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BTL_LTWEB.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Masp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Soluong")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username1")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("Username1");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("BTL_LTWEB.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username1");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BTL_LTWEB.Models.Product", b =>
                {
                    b.Property<string>("Masp")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("MaSP");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HangSX");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HinhAnh");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenSP");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Gia");

                    b.Property<int>("RateCount")
                        .HasColumnType("int")
                        .HasColumnName("SoDanhGia");

                    b.Property<float>("Star")
                        .HasColumnType("real")
                        .HasColumnName("Sao");

                    b.HasKey("Masp");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("BTL_LTWEB.Models.ProductDetail", b =>
                {
                    b.Property<string>("Masp")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("MaSP");

                    b.Property<string>("Battery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Pin");

                    b.Property<string>("Camera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CameraSau");

                    b.Property<string>("CameraFront")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CameraTruoc");

                    b.Property<string>("Cpu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CPU");

                    b.Property<string>("Ram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RAM");

                    b.Property<string>("Rom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ROM");

                    b.Property<string>("Screen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ManHinh");

                    b.Property<string>("WaterProof")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ChongNuoc");

                    b.HasKey("Masp");

                    b.ToTable("ChiTietSanPham");
                });

            modelBuilder.Entity("BTL_LTWEB.Models.Promo", b =>
                {
                    b.Property<string>("Masp")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("MaSP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenKM");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GiaTri");

                    b.HasKey("Masp");

                    b.ToTable("KhuyenMai");
                });

            modelBuilder.Entity("BTL_LTWEB.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BTL_LTWEB.Models.CartItem", b =>
                {
                    b.HasOne("BTL_LTWEB.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");

                    b.HasOne("BTL_LTWEB.Models.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("Username1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BTL_LTWEB.Models.Order", b =>
                {
                    b.HasOne("BTL_LTWEB.Models.User", null)
                        .WithMany("Donhang")
                        .HasForeignKey("Username1");
                });

            modelBuilder.Entity("BTL_LTWEB.Models.ProductDetail", b =>
                {
                    b.HasOne("BTL_LTWEB.Models.Product", "Product")
                        .WithOne("Detail")
                        .HasForeignKey("BTL_LTWEB.Models.ProductDetail", "Masp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BTL_LTWEB.Models.Promo", b =>
                {
                    b.HasOne("BTL_LTWEB.Models.Product", "Product")
                        .WithOne("Promo")
                        .HasForeignKey("BTL_LTWEB.Models.Promo", "Masp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BTL_LTWEB.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BTL_LTWEB.Models.Product", b =>
                {
                    b.Navigation("Detail")
                        .IsRequired();

                    b.Navigation("Promo")
                        .IsRequired();
                });

            modelBuilder.Entity("BTL_LTWEB.Models.User", b =>
                {
                    b.Navigation("Donhang");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
